version: '3.8'

services:
  sharex-manager:
    build:
      context: .
      target: runner
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
      - .env.local
      - .env.production
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - NEXT_PUBLIC_IMAGE_DOMAIN=${NEXT_PUBLIC_IMAGE_DOMAIN:-img.ascencia.re}
      - NEXT_PUBLIC_APP_DOMAIN=${NEXT_PUBLIC_APP_DOMAIN:-ascencia.re}
      - TZ=Europe/Paris
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Montage des dossiers locaux
      - ./config:/app/config
      - ./uploads:/app/uploads:delegated
      - ./data:/app/data
      - next-cache:/app/.next/cache

volumes:
  next-cache:
