name: Test and Build Next.js Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
      TZ: Europe/Paris

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create required directories
        run: |
          mkdir -p data config
          chmod 777 data config

      - name: Install dependencies
        run: bun install

      - name: Install module dependencies
        run: |
          echo "Installing dependencies for modules..."
          for module_dir in modules/*/; do
            if [ -f "$module_dir/package.json" ]; then
              echo "Installing dependencies for module: $module_dir"
              cd "$module_dir"
              bun install
              cd - > /dev/null
            else
              echo "No package.json found in $module_dir, skipping..."
            fi
          done
          echo "Module dependencies installation completed"

      - name: Run tests
        run: |
          echo "Running tests..."
          bun test --run --reporter=verbose
          echo "Tests completed successfully"

      - name: Run test coverage
        run: |
          echo "Running test coverage..."
          bun test --run --coverage --reporter=verbose
          echo "Test coverage completed successfully"

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: coverage/

  build:
    runs-on: ubuntu-latest
    needs: test
    
    env:
      PORT: 3000
      NODE_ENV: production
      AUTH_SECRET: ${{ secrets.AUTH_SECRET || 'github-action-secret-placeholder' }}
      AUTH_URL: ${{ secrets.AUTH_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:3000' }}
      NEXT_PUBLIC_IMAGE_DOMAIN: ${{ secrets.NEXT_PUBLIC_IMAGE_DOMAIN || 'img.ascencia.re' }}
      NEXT_PUBLIC_APP_DOMAIN: ${{ secrets.NEXT_PUBLIC_APP_DOMAIN || 'ascencia.re' }}
      TZ: Europe/Paris
      HOSTNAME: 0.0.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create required directories
        run: |
          mkdir -p .next/static uploads uploads/thumbnails data config
          chmod 777 uploads uploads/thumbnails data config

      - name: Install dependencies
        run: bun install

      - name: Install module dependencies
        run: |
          echo "Installing dependencies for modules..."
          for module_dir in modules/*/; do
            if [ -f "$module_dir/package.json" ]; then
              echo "Installing dependencies for module: $module_dir"
              cd "$module_dir"
              bun install
              cd - > /dev/null
            else
              echo "No package.json found in $module_dir, skipping..."
            fi
          done
          echo "Module dependencies installation completed"

      - name: Build
        run: bun --bun run build
        
      - name: Verify build output
        run: |
          if [ ! -d ".next/standalone" ] || [ ! -d ".next/static" ]; then
            echo "Build failed: standalone or static directories not found"
            exit 1
          fi
          echo "Build successful: standalone and static directories found"
          ls -la .next/standalone
          ls -la .next/static

      - name: Create cache directory
        run: mkdir -p .next/cache && chmod 777 .next/cache

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            .next/standalone
            .next/static
            modules/*/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}-${{ hashFiles('modules/**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}- 